spring.application.name=taskmanager
# Enable the H2 Console so we can see the DB in the browser
spring.h2.console.enabled=true
# Set the URL for the database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# This ensures the table is created automatically
spring.jpa.hibernate.ddl-auto=update